// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "smartwatch_app.h"
#if defined(MTB_DISPLAY_CO5300)
#include "mtb_display_co5300.h"
#endif

lv_obj_t * ui_AnalogScreen = NULL;
lv_obj_t * ui_AnalogScreenBatteryPanel = NULL;
lv_obj_t * ui_AnalogScreenBatteryLevel = NULL;
lv_obj_t * ui_AnalogScreenBatteryImg = NULL;
lv_obj_t * ui_AnalogScreenDatePanel = NULL;
lv_obj_t * ui_AnalogScreenDateLabel = NULL;
lv_obj_t * ui_AnalogScreenMonthLabel = NULL;
lv_obj_t * ui_AnalogScreenYearLabel = NULL;
lv_obj_t * ui_AnalogScreenDayLabel = NULL;
lv_obj_t * ui_AnalogScreenWeatherPanel = NULL;
lv_obj_t * ui_AnalogScreenWeatherIcon = NULL;
lv_obj_t * ui_AnalogScreenWeatherLabel = NULL;
lv_obj_t * ui_AnalogScreenInfineonImg = NULL;
lv_obj_t * ui_AnalogScreenStepsArc = NULL;
lv_obj_t * ui_AnalogScreenStepsPanel = NULL;
lv_obj_t * ui_AnalogScreenStepsCountLabel = NULL;
lv_obj_t * ui_AnalogScreenStepImg = NULL;
lv_obj_t * ui_AnalogScreenStepsPercentLabel = NULL;
lv_obj_t * ui_AnalogScreenClockPanel = NULL;
lv_obj_t * ui_AnalogScreenSecHand = NULL;
lv_obj_t * ui_AnalogScreenMinHand = NULL;
lv_obj_t * ui_AnalogScreenHourHand = NULL;
lv_obj_t * ui_AnalogScreenWeatherButton = NULL;
// event funtions
void ui_event_AnalogScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_DigitalScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_DigitalScreen_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        AnalogClockSecHandAnim_Animation(ui_AnalogScreenSecHand, 0);
        AnalogClockMinHandAnim_Animation(ui_AnalogScreenMinHand, 0);
        AnalogClockHourHandAnim_Animation(ui_AnalogScreenHourHand, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_DigitalScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_DigitalScreen_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_HealthScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_HealthScreen_screen_init);
    }
}

void ui_event_AnalogScreenStepsArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_AnalogScreenStepsPercentLabel, target, "", "%");
        /* Treat the steps arc as brightness control on ROUND display */
        brightness = (uint8_t)lv_arc_get_value(target);
#if defined(MTB_DISPLAY_CO5300)
        mtb_display_co5300_set_brightness(&base->GFXSS_MIPIDSI, SET_BRIGHTNESS(brightness));
#endif
    }
}

void ui_event_AnalogScreenWeatherButton_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WeatherScreen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_WeatherScreen1_screen_init);
    }
}

// build funtions

void ui_AnalogScreen_screen_init(void)
{
    ui_AnalogScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AnalogScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_AnalogScreen, &ui_img_black_watch_face_3_cpy_nodigit_png,
                                  (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_image_tiled(ui_AnalogScreen, true, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_left(ui_AnalogScreen, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_right(ui_AnalogScreen, 25, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_top(ui_AnalogScreen, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_bottom(ui_AnalogScreen, 0, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenBatteryPanel = lv_obj_create(ui_AnalogScreen);
    lv_obj_set_width(ui_AnalogScreenBatteryPanel, 100);
    lv_obj_set_height(ui_AnalogScreenBatteryPanel, 26);
    lv_obj_set_x(ui_AnalogScreenBatteryPanel, 0);
    lv_obj_set_y(ui_AnalogScreenBatteryPanel, -182);
    lv_obj_set_align(ui_AnalogScreenBatteryPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AnalogScreenBatteryPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AnalogScreenBatteryPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_AnalogScreenBatteryPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_AnalogScreenBatteryPanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_color(ui_AnalogScreenBatteryPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_AnalogScreenBatteryPanel,255,(lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_AnalogScreenBatteryPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenBatteryLevel = lv_label_create(ui_AnalogScreenBatteryPanel);
    lv_obj_set_width(ui_AnalogScreenBatteryLevel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenBatteryLevel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenBatteryLevel, 11);
    lv_obj_set_y(ui_AnalogScreenBatteryLevel, -1);
    lv_obj_set_align(ui_AnalogScreenBatteryLevel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalogScreenBatteryLevel, "86%");
    lv_obj_set_style_text_color(ui_AnalogScreenBatteryLevel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_AnalogScreenBatteryLevel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_AnalogScreenBatteryLevel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenBatteryImg = lv_image_create(ui_AnalogScreenBatteryPanel);
    lv_image_set_src(ui_AnalogScreenBatteryImg, &ui_img_flash_png);
    lv_obj_set_width(ui_AnalogScreenBatteryImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenBatteryImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenBatteryImg, -27);
    lv_obj_set_y(ui_AnalogScreenBatteryImg, 0);
    lv_obj_set_align(ui_AnalogScreenBatteryImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnalogScreenBatteryImg, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_AnalogScreenBatteryImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AnalogScreenDatePanel = lv_obj_create(ui_AnalogScreen);
    lv_obj_set_width(ui_AnalogScreenDatePanel, 160);
    lv_obj_set_height(ui_AnalogScreenDatePanel, 80);
    lv_obj_set_x(ui_AnalogScreenDatePanel, 9);
    lv_obj_set_y(ui_AnalogScreenDatePanel, -127);
    lv_obj_set_align(ui_AnalogScreenDatePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AnalogScreenDatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AnalogScreenDatePanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_AnalogScreenDatePanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_AnalogScreenDatePanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_AnalogScreenDatePanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_AnalogScreenDatePanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenDateLabel = lv_label_create(ui_AnalogScreenDatePanel);
    lv_obj_set_width(ui_AnalogScreenDateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenDateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenDateLabel, -58);
    lv_obj_set_y(ui_AnalogScreenDateLabel, -11);
    lv_obj_set_align(ui_AnalogScreenDateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalogScreenDateLabel, "01");
    lv_obj_set_style_text_color(ui_AnalogScreenDateLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_AnalogScreenDateLabel,(lv_opa_t)255,(lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_AnalogScreenDateLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenMonthLabel = lv_label_create(ui_AnalogScreenDatePanel);
    lv_obj_set_width(ui_AnalogScreenMonthLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenMonthLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenMonthLabel, -11);
    lv_obj_set_y(ui_AnalogScreenMonthLabel, -11);
    lv_obj_set_align(ui_AnalogScreenMonthLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalogScreenMonthLabel, "JAN");
    lv_obj_set_style_text_color(ui_AnalogScreenMonthLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_AnalogScreenMonthLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_AnalogScreenMonthLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenYearLabel = lv_label_create(ui_AnalogScreenDatePanel);
    lv_obj_set_width(ui_AnalogScreenYearLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenYearLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenYearLabel, 46);
    lv_obj_set_y(ui_AnalogScreenYearLabel, -11);
    lv_obj_set_align(ui_AnalogScreenYearLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalogScreenYearLabel, "2025");
    lv_obj_set_style_text_color(ui_AnalogScreenYearLabel, lv_color_hex(0x6B6B6B), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_AnalogScreenYearLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_AnalogScreenYearLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenDayLabel = lv_label_create(ui_AnalogScreenDatePanel);
    lv_obj_set_width(ui_AnalogScreenDayLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenDayLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenDayLabel, -9);
    lv_obj_set_y(ui_AnalogScreenDayLabel, 19);
    lv_obj_set_align(ui_AnalogScreenDayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalogScreenDayLabel, "WED");
    lv_obj_set_style_text_color(ui_AnalogScreenDayLabel, lv_color_hex(0x6B6B6B), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_AnalogScreenDayLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_AnalogScreenDayLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenWeatherPanel = lv_obj_create(ui_AnalogScreen);
    lv_obj_set_width(ui_AnalogScreenWeatherPanel, 73);
    lv_obj_set_height(ui_AnalogScreenWeatherPanel, 68);
    lv_obj_set_x(ui_AnalogScreenWeatherPanel, -107);
    lv_obj_set_y(ui_AnalogScreenWeatherPanel, -94);
    lv_obj_set_align(ui_AnalogScreenWeatherPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AnalogScreenWeatherPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AnalogScreenWeatherPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_AnalogScreenWeatherPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_AnalogScreenWeatherPanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_AnalogScreenWeatherPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenWeatherIcon = lv_image_create(ui_AnalogScreenWeatherPanel);
    lv_image_set_src(ui_AnalogScreenWeatherIcon, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_AnalogScreenWeatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenWeatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenWeatherIcon, -10);
    lv_obj_set_y(ui_AnalogScreenWeatherIcon, 16);
    lv_obj_set_align(ui_AnalogScreenWeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnalogScreenWeatherIcon, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_AnalogScreenWeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AnalogScreenWeatherLabel = lv_label_create(ui_AnalogScreenWeatherPanel);
    lv_obj_set_width(ui_AnalogScreenWeatherLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenWeatherLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenWeatherLabel, -6);
    lv_obj_set_y(ui_AnalogScreenWeatherLabel, -17);
    lv_obj_set_align(ui_AnalogScreenWeatherLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalogScreenWeatherLabel, "25°");
    lv_obj_set_style_text_color(ui_AnalogScreenWeatherLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_AnalogScreenWeatherLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_AnalogScreenWeatherLabel, &ui_font_H1, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenInfineonImg = lv_image_create(ui_AnalogScreen);
    lv_obj_set_width(ui_AnalogScreenInfineonImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenInfineonImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenInfineonImg, 1);
    lv_obj_set_y(ui_AnalogScreenInfineonImg, 91);
    lv_obj_set_align(ui_AnalogScreenInfineonImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnalogScreenInfineonImg, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_AnalogScreenInfineonImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AnalogScreenStepsArc = lv_arc_create(ui_AnalogScreen);
    lv_obj_set_width(ui_AnalogScreenStepsArc, 380);
    lv_obj_set_height(ui_AnalogScreenStepsArc, 372);
    lv_obj_set_x(ui_AnalogScreenStepsArc, -3);
    lv_obj_set_y(ui_AnalogScreenStepsArc, 9);
    lv_obj_set_align(ui_AnalogScreenStepsArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_AnalogScreenStepsArc, 80);
    lv_arc_set_bg_angles(ui_AnalogScreenStepsArc, 10, 80);
    lv_arc_set_rotation(ui_AnalogScreenStepsArc, 100);
    lv_obj_set_style_arc_color(ui_AnalogScreenStepsArc, lv_color_hex(0x303030), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_opa(ui_AnalogScreenStepsArc, 255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_width(ui_AnalogScreenStepsArc, 7, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_rounded(ui_AnalogScreenStepsArc, true, (lv_style_selector_t)LV_PART_MAIN);

    lv_obj_set_style_arc_color(ui_AnalogScreenStepsArc, lv_color_hex(0xB0E14A), LV_PART_INDICATOR);
    lv_obj_set_style_arc_opa(ui_AnalogScreenStepsArc, 255, LV_PART_INDICATOR);
    lv_obj_set_style_arc_width(ui_AnalogScreenStepsArc, 7, LV_PART_INDICATOR);
    lv_obj_set_style_arc_rounded(ui_AnalogScreenStepsArc, true, LV_PART_INDICATOR);

    lv_obj_set_style_bg_color(ui_AnalogScreenStepsArc, lv_color_hex(0xB0E14A), LV_PART_KNOB);
    lv_obj_set_style_bg_opa(ui_AnalogScreenStepsArc,(lv_opa_t) 255, LV_PART_KNOB);

    ui_AnalogScreenStepsPanel = lv_obj_create(ui_AnalogScreen);
    lv_obj_set_width(ui_AnalogScreenStepsPanel, 100);
    lv_obj_set_height(ui_AnalogScreenStepsPanel, 26);
    lv_obj_set_x(ui_AnalogScreenStepsPanel, 5);
    lv_obj_set_y(ui_AnalogScreenStepsPanel, 156);
    lv_obj_set_align(ui_AnalogScreenStepsPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AnalogScreenStepsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AnalogScreenStepsPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_AnalogScreenStepsPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_AnalogScreenStepsPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_color(ui_AnalogScreenStepsPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_AnalogScreenStepsPanel, 255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_AnalogScreenStepsPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenStepsCountLabel = lv_label_create(ui_AnalogScreenStepsPanel);
    lv_obj_set_width(ui_AnalogScreenStepsCountLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenStepsCountLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenStepsCountLabel, 2);
    lv_obj_set_y(ui_AnalogScreenStepsCountLabel, 0);
    lv_obj_set_align(ui_AnalogScreenStepsCountLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalogScreenStepsCountLabel, "0");
    lv_obj_set_style_text_color(ui_AnalogScreenStepsCountLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_AnalogScreenStepsCountLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_AnalogScreenStepsCountLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenStepImg = lv_image_create(ui_AnalogScreenStepsPanel);
    lv_image_set_src(ui_AnalogScreenStepImg, &ui_img_step_png);
    lv_obj_set_width(ui_AnalogScreenStepImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenStepImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenStepImg, -33);
    lv_obj_set_y(ui_AnalogScreenStepImg, 1);
    lv_obj_set_align(ui_AnalogScreenStepImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnalogScreenStepImg, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_AnalogScreenStepImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AnalogScreenStepsPercentLabel = lv_label_create(ui_AnalogScreen);
    lv_obj_set_width(ui_AnalogScreenStepsPercentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenStepsPercentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenStepsPercentLabel, -145);
    lv_obj_set_y(ui_AnalogScreenStepsPercentLabel, 9);
    lv_obj_set_align(ui_AnalogScreenStepsPercentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AnalogScreenStepsPercentLabel, "80%");
    lv_obj_set_style_text_color(ui_AnalogScreenStepsPercentLabel, lv_color_hex(0xEE1E1E), LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AnalogScreenStepsPercentLabel, (lv_opa_t)255,LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AnalogScreenStepsPercentLabel, &ui_font_Subtitle, LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);

    ui_AnalogScreenClockPanel = lv_obj_create(ui_AnalogScreen);
    lv_obj_set_width(ui_AnalogScreenClockPanel, 350);
    lv_obj_set_height(ui_AnalogScreenClockPanel, 350);
    lv_obj_set_x(ui_AnalogScreenClockPanel, 2);
    lv_obj_set_y(ui_AnalogScreenClockPanel, -6);
    lv_obj_set_align(ui_AnalogScreenClockPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AnalogScreenClockPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AnalogScreenClockPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_AnalogScreenClockPanel,(lv_opa_t) 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_AnalogScreenClockPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_AnalogScreenClockPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_AnalogScreenSecHand = lv_image_create(ui_AnalogScreenClockPanel);
    lv_image_set_src(ui_AnalogScreenSecHand, &ui_img_clockwise_sec_png);
    lv_obj_set_width(ui_AnalogScreenSecHand, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenSecHand, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenSecHand, 0);
    lv_obj_set_y(ui_AnalogScreenSecHand, -67);
    lv_obj_set_align(ui_AnalogScreenSecHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnalogScreenSecHand, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_AnalogScreenSecHand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_AnalogScreenSecHand, 15, 155);
    lv_image_set_rotation(ui_AnalogScreenSecHand, 12000);

    ui_AnalogScreenMinHand = lv_image_create(ui_AnalogScreenClockPanel);
    lv_image_set_src(ui_AnalogScreenMinHand, &ui_img_clockwise_min_png);
    lv_obj_set_width(ui_AnalogScreenMinHand, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenMinHand, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenMinHand, 0);
    lv_obj_set_y(ui_AnalogScreenMinHand, -75);
    lv_obj_set_align(ui_AnalogScreenMinHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnalogScreenMinHand, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_AnalogScreenMinHand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_AnalogScreenMinHand, 9, 148);

    ui_AnalogScreenHourHand = lv_image_create(ui_AnalogScreenClockPanel);
    lv_image_set_src(ui_AnalogScreenHourHand, &ui_img_clockwise_hour_png);
    lv_obj_set_width(ui_AnalogScreenHourHand, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AnalogScreenHourHand, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AnalogScreenHourHand, 0);
    lv_obj_set_y(ui_AnalogScreenHourHand, -45);
    lv_obj_set_align(ui_AnalogScreenHourHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AnalogScreenHourHand, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_AnalogScreenHourHand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_AnalogScreenHourHand, 9, 93);

    ui_AnalogScreenWeatherButton = ui_Button_create(ui_AnalogScreen);
    lv_obj_set_width(ui_AnalogScreenWeatherButton, 58);
    lv_obj_set_height(ui_AnalogScreenWeatherButton, 68);
    lv_obj_set_x(ui_AnalogScreenWeatherButton, 153);
    lv_obj_set_y(ui_AnalogScreenWeatherButton, 90);
    lv_obj_set_style_bg_color(ui_AnalogScreenWeatherButton, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_AnalogScreenWeatherButton, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    lv_image_set_src(ui_comp_get_child(ui_AnalogScreenWeatherButton, UI_COMP_BUTTON_BTNICON),
                     &ui_img_weather_sun_cloud_png);
    lv_obj_set_x(ui_comp_get_child(ui_AnalogScreenWeatherButton, UI_COMP_BUTTON_BTNICON), -10);
    lv_obj_set_y(ui_comp_get_child(ui_AnalogScreenWeatherButton, UI_COMP_BUTTON_BTNICON), -9);

    lv_image_set_src(ui_comp_get_child(ui_AnalogScreenWeatherButton, UI_COMP_BUTTON_BTNBAR), &ui_img_btn_bg_3_png);
    lv_obj_set_x(ui_comp_get_child(ui_AnalogScreenWeatherButton, UI_COMP_BUTTON_BTNBAR), 11);
    lv_obj_set_y(ui_comp_get_child(ui_AnalogScreenWeatherButton, UI_COMP_BUTTON_BTNBAR), 10);

    lv_obj_add_event_cb(ui_AnalogScreenStepsArc, ui_event_AnalogScreenStepsArc, (lv_event_code_t)LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AnalogScreenWeatherButton, ui_event_AnalogScreenWeatherButton_Button, (lv_event_code_t)LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AnalogScreen, ui_event_AnalogScreen, (lv_event_code_t)LV_EVENT_ALL, NULL);

}

void ui_AnalogScreen_screen_destroy(void)
{
    if(ui_AnalogScreen) lv_obj_del(ui_AnalogScreen);

    // NULL screen variables
    ui_AnalogScreen = NULL;
    ui_AnalogScreenBatteryPanel = NULL;
    ui_AnalogScreenBatteryLevel = NULL;
    ui_AnalogScreenBatteryImg = NULL;
    ui_AnalogScreenDatePanel = NULL;
    ui_AnalogScreenDateLabel = NULL;
    ui_AnalogScreenMonthLabel = NULL;
    ui_AnalogScreenYearLabel = NULL;
    ui_AnalogScreenDayLabel = NULL;
    ui_AnalogScreenWeatherPanel = NULL;
    ui_AnalogScreenWeatherIcon = NULL;
    ui_AnalogScreenWeatherLabel = NULL;
    ui_AnalogScreenInfineonImg = NULL;
    ui_AnalogScreenStepsArc = NULL;
    ui_AnalogScreenStepsPanel = NULL;
    ui_AnalogScreenStepsCountLabel = NULL;
    ui_AnalogScreenStepImg = NULL;
    ui_AnalogScreenStepsPercentLabel = NULL;
    ui_AnalogScreenClockPanel = NULL;
    ui_AnalogScreenSecHand = NULL;
    ui_AnalogScreenMinHand = NULL;
    ui_AnalogScreenHourHand = NULL;
    ui_AnalogScreenWeatherButton = NULL;

}
