// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_LPScreen = NULL;
lv_obj_t * ui_LPScreenTimePanel = NULL;
lv_obj_t * ui_LPScreenHourLabel = NULL;
lv_obj_t * ui_LPScreenClockDots = NULL;
lv_obj_t * ui_LPScreenMinLabel = NULL;
lv_obj_t * ui_LPScreenStepsPanel = NULL;
lv_obj_t * ui_LPScreenStepsLabel = NULL;
lv_obj_t * ui_LPScreenStepImg = NULL;
lv_obj_t * ui_LPScreenDatePanel = NULL;
lv_obj_t * ui_LPScreenDateLabel = NULL;
lv_obj_t * ui_LPScreenMonthLabel = NULL;
lv_obj_t * ui_LPScreenDayLabel = NULL;
// event funtions

// build funtions

void ui_LPScreen_screen_init(void)
{
    ui_LPScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_LPScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LPScreen, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_LPScreen, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_left(ui_LPScreen, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_right(ui_LPScreen, 20, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_top(ui_LPScreen, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_bottom(ui_LPScreen, 0, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenTimePanel = lv_obj_create(ui_LPScreen);
    lv_obj_set_width(ui_LPScreenTimePanel, 350);
    lv_obj_set_height(ui_LPScreenTimePanel, 90);
    lv_obj_set_x(ui_LPScreenTimePanel, -1);
    lv_obj_set_y(ui_LPScreenTimePanel, -42);
    lv_obj_set_align(ui_LPScreenTimePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LPScreenTimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LPScreenTimePanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_LPScreenTimePanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_LPScreenTimePanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_LPScreenTimePanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenHourLabel = lv_label_create(ui_LPScreenTimePanel);
    lv_obj_set_width(ui_LPScreenHourLabel, 150);
    lv_obj_set_height(ui_LPScreenHourLabel, 90);
    lv_obj_set_x(ui_LPScreenHourLabel, -11);
    lv_obj_set_y(ui_LPScreenHourLabel, 7);
    lv_obj_set_align(ui_LPScreenHourLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LPScreenHourLabel, "12");
    lv_obj_set_style_text_color(ui_LPScreenHourLabel, lv_color_hex(0x6B6B6B), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenHourLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenHourLabel, &ui_font_Number_big, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenClockDots = lv_label_create(ui_LPScreenTimePanel);
    lv_obj_set_width(ui_LPScreenClockDots, 23);
    lv_obj_set_height(ui_LPScreenClockDots, 109);
    lv_obj_set_x(ui_LPScreenClockDots, -1);
    lv_obj_set_y(ui_LPScreenClockDots, 7);
    lv_obj_set_align(ui_LPScreenClockDots, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LPScreenClockDots, ":");
    lv_obj_set_style_text_color(ui_LPScreenClockDots, lv_color_hex(0xB1ADAD), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenClockDots, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenClockDots, &ui_font_Number_big, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenMinLabel = lv_label_create(ui_LPScreenTimePanel);
    lv_obj_set_width(ui_LPScreenMinLabel, 150);
    lv_obj_set_height(ui_LPScreenMinLabel, 90);
    lv_obj_set_x(ui_LPScreenMinLabel, 17);
    lv_obj_set_y(ui_LPScreenMinLabel, 7);
    lv_obj_set_align(ui_LPScreenMinLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LPScreenMinLabel, "00");
    lv_obj_set_style_text_color(ui_LPScreenMinLabel, lv_color_hex(0xEE1E1E), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenMinLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenMinLabel, &ui_font_Number_big, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenStepsPanel = lv_obj_create(ui_LPScreen);
    lv_obj_set_width(ui_LPScreenStepsPanel, 100);
    lv_obj_set_height(ui_LPScreenStepsPanel, 26);
    lv_obj_set_x(ui_LPScreenStepsPanel, 1);
    lv_obj_set_y(ui_LPScreenStepsPanel, 153);
    lv_obj_set_align(ui_LPScreenStepsPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LPScreenStepsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LPScreenStepsPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_LPScreenStepsPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_LPScreenStepsPanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_color(ui_LPScreenStepsPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_LPScreenStepsPanel, 255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_LPScreenStepsPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenStepsLabel = lv_label_create(ui_LPScreenStepsPanel);
    lv_obj_set_width(ui_LPScreenStepsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LPScreenStepsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LPScreenStepsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LPScreenStepsLabel, "0");
    lv_obj_set_style_text_color(ui_LPScreenStepsLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenStepsLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenStepsLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenStepImg = lv_image_create(ui_LPScreenStepsPanel);
    lv_image_set_src(ui_LPScreenStepImg, &ui_img_step_png);
    lv_obj_set_width(ui_LPScreenStepImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LPScreenStepImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LPScreenStepImg, -36);
    lv_obj_set_y(ui_LPScreenStepImg, 0);
    lv_obj_set_align(ui_LPScreenStepImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LPScreenStepImg, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_LPScreenStepImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LPScreenDatePanel = lv_obj_create(ui_LPScreen);
    lv_obj_set_width(ui_LPScreenDatePanel, 289);
    lv_obj_set_height(ui_LPScreenDatePanel, 44);
    lv_obj_set_x(ui_LPScreenDatePanel, -2);
    lv_obj_set_y(ui_LPScreenDatePanel, 53);
    lv_obj_set_align(ui_LPScreenDatePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LPScreenDatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LPScreenDatePanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_LPScreenDatePanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_LPScreenDatePanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_LPScreenDatePanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenDateLabel = lv_label_create(ui_LPScreenDatePanel);
    lv_obj_set_width(ui_LPScreenDateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LPScreenDateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LPScreenDateLabel, -116);
    lv_obj_set_y(ui_LPScreenDateLabel, 0);
    lv_obj_set_align(ui_LPScreenDateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LPScreenDateLabel, "01");
    lv_obj_set_style_text_color(ui_LPScreenDateLabel, lv_color_hex(0xFF0000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenDateLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenDateLabel, &ui_font_H1, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenMonthLabel = lv_label_create(ui_LPScreenDatePanel);
    lv_obj_set_width(ui_LPScreenMonthLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LPScreenMonthLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LPScreenMonthLabel, -21);
    lv_obj_set_y(ui_LPScreenMonthLabel, 0);
    lv_obj_set_align(ui_LPScreenMonthLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LPScreenMonthLabel, "JAN");
    lv_obj_set_style_text_color(ui_LPScreenMonthLabel, lv_color_hex(0xFF0000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenMonthLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenMonthLabel, &ui_font_H1, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenDayLabel = lv_label_create(ui_LPScreenDatePanel);
    lv_obj_set_width(ui_LPScreenDayLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LPScreenDayLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LPScreenDayLabel, 92);
    lv_obj_set_y(ui_LPScreenDayLabel, 0);
    lv_obj_set_align(ui_LPScreenDayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LPScreenDayLabel, "WED");
    lv_obj_set_style_text_color(ui_LPScreenDayLabel, lv_color_hex(0xFF0000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenDayLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenDayLabel, &ui_font_H1, (lv_style_selector_t)LV_PART_MAIN);

}

void ui_LPScreen_screen_destroy(void)
{
    if(ui_LPScreen) lv_obj_del(ui_LPScreen);

    // NULL screen variables
    ui_LPScreen = NULL;
    ui_LPScreenTimePanel = NULL;
    ui_LPScreenHourLabel = NULL;
    ui_LPScreenClockDots = NULL;
    ui_LPScreenMinLabel = NULL;
    ui_LPScreenStepsPanel = NULL;
    ui_LPScreenStepsLabel = NULL;
    ui_LPScreenStepImg = NULL;
    ui_LPScreenDatePanel = NULL;
    ui_LPScreenDateLabel = NULL;
    ui_LPScreenMonthLabel = NULL;
    ui_LPScreenDayLabel = NULL;

}
